site_name: IaC
site_url: https://example.com/
nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'IaC Documentation': 'docs.md'
theme:
  logo: assets/Canoja Technologies.svg
  icon:
    repo: fontawesome/brands/git-alt
  favicon: images/Canoja_Leaf_icon.png
  name: material
  features:
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
  font:
    text: Oxygen
    code: Roboto Mono
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      accent: green
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: green
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk
  generator: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/NareshChinnusamy/iac-docs.git
repo_name: iac-docs
edit_uri: ""



  